INSERT INTO users (name, email, password) 
VALUES ('Captain Waffle', 'captain@waffle.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'), 
('Sugar Booger', 'sugar@booger.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'), 
('Dr. Pickles', 'drpickles@pickles.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.');


INSERT INTO properties (owner_id, 
  title, 
  description, 
  thumbnail_photo_url, 
  cover_photo_url, 
  cost_per_night, 
  parking_spaces, 
  number_of_bathrooms, 
  number_of_bedrooms, 
  street, 
  city,
  province,
  country,
  post_code,
  active)
VALUES (1, 
  'The Perfect Beach House',
  'This is the perfect beach house for your next getaway!',
  'www.example.com/image.jpg',
  'www.example.com/cover.jpg',
  150.00,
  4,
  2,
  4,
  '123 Main Street',
  'Toronto',
  'ON',
  'Canada',
  'M2M 3M3',
  TRUE), 
  (2,
  'Luxury Mansion',
  'Cozy and luxurious mansion located in the heart of the city',
  'www.example.com/luxury_mansion.jpg',
  'www.example.com/luxury_mansion_cover.jpg',
  200.00,
  3,
  3,
  5,
  '456 second Street',
  'Barrie',
  'Ontario',
  'Canada',
  'L1A1B2',
  TRUE), 
  (3,
  'My Beachside Bungalow',
  'A cozy cottage beside the ocean.',
  'www.example.com/beach_house.jpg',
  'www.example.com/beach_house_cover.jpg',
  175.00,
  1,
  2,
  2,
  '123 Beachside Lane',
  'Toronto',
  'Ontario',
  'Canada',
  'M4B 1B2',
  TRUE);

INSERT INTO reservations (start_date, end_date, property_id, guest_id)
VALUES ('2018-09-11', '2018-09-26', 1, 3),
  ('2019-01-04', '2019-02-01', 2, 1),
  ('2021-10-01', '2021-10-14', 3, 2);

INSERT INTO property_reviews (reservation_id, guest_id, property_id, message, rating)
VALUES (1, 3, 1, 'message', 4), 
  (2, 1, 2, 'message', 3),
  (3, 2, 3, 'message', 4);